AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{ cookiecutter.project_name }}

  Alexa Skill SAM Template for {{ cookiecutter.project_name }}

Globals:
  Function:
    Timeout: 10

Resources:
  HttpProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: alexa_skill/
      Handler: http.lambda_handler
      {%- if cookiecutter.runtime == 'nodejs6.10' %}
      Runtime: nodejs6.10
      {%- elif cookiecutter.runtime =='nodejs4.3' %}
      Runtime: nodejs4.3
      {%- else %}
      Runtime: nodejs8.10
      {%- endif %}
      Events:
        HttpProxy:
          Type: Api
          Properties:
            Path: /
            Method: post
